general:
  productiveBranch: 'main'
  maven:
    projectSettingsFile : 'settings.xml'
  gitCredentialsId: 1103b590-2c79-48bc-a5be-ff2272e78840
  gitSshKeyCredentialsId: 1103b590-2c79-48bc-a5be-ff2272e78840
  buildTool: 'maven'
steps:
  mavenExecute:
    dockerImage: maven:3.6.3-jdk-11-slim
