general:
  productiveBranch: 'main'
  collectTelemetryData: false
  xMake:
    buildQuality: 'Milestone'
    novaCredentialsId: 'xmakeNova'
  maven:
    projectSettingsFile : '.pipeline/settings.xml'
  gitCredentialsId: 'SHA256:IXIvax2XosAQi9monapSa6Ys0pLgx/k74EOYuaPQ7zM'
  gitSshKeyCredentialsId: 'SHA256:IXIvax2XosAQi9monapSa6Ys0pLgx/k74EOYuaPQ7zM '
  buildTool: 'maven'
  
steps:
 dockerExecuteOnKubernetes:
    containerPullImageFlags:
      's4sdk/docker-node-browsers': true
 
 mavenExecute:
    dockerImage: maven:3.6.3-jdk-11-slim
 
artifactPrepareVersion:
    versioningType: 'cloud'
    gitSshKeyCredentialsId: 'SHA256:IXIvax2XosAQi9monapSa6Ys0pLgx/k74EOYuaPQ7zM'
    
mavenBuild:
    script: this
    buildTarget: 'CF'
    
nexusUpload:
    script: this
    url: http://artefact.focus.com.tn:8081/repository/maven-public/
    
cloudFoundryDeploy:
    cloudFoundry:
      org: '35ba65d0-f317-424f-bfc0-8f3fcc24781a'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
      apiEndpoint: 'https://api.cf.us10.hana.ondemand.com'
      
stages:
  checksPublishResults:
    script: this
    
  frontendUnitTests:
    dockerImage: ppiper/node-browsers

  frontendIntegrationTests:
    dockerImage: ppiper/node-browsers
    
postActions:
  sendNotification:
    skipFeatureBranches: false
